services:
  python-http-service:
    container_name: python-http
    image: $IMAGE
    ports:
      - 1234:8000
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
